name: dsci-524-proj-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab
  - ipykernel
  - conda-lock
  - hatch
  - copier
  - pandas
  - pip
  - pip:
      - quartodoc
  - altair
  - pytest
  - pytest-cov
  - faker

prefix: C:\Users\jjyor\miniforge3\envs\dsci-524-proj-env
