name: dsci-524-proj-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - conda-lock
  - hatch
  - copier
  - pandas
  - pip
  - altair
  - pytest
  - faker
prefix: C:\Users\jjyor\miniforge3\envs\dsci-524-proj-env
